layout_spectrum: 0.9211754
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.856668782653287
  brandStrength: 0.2784515
  rhythmicContrast: 0.6672927553299814
  brandColors:
    - '#8EC4E7'
    - '#B36E69'
    - '#000D16'
    - '#4581BB'
    - '#FBE280'
  lightness: 0.3877902417443693
typography_spectrum: 0.8866605
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: "Brent Franklin's Site"
