layout_spectrum: 0.6805037
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 1
  lightness: 0.4846082
  brandColors:
    - '#000000'
    - '#A8AAA9'
    - '#373938'
    - '#585A59'
    - '#FCFEFD'
  rhythmicContrast: 1
typography_spectrum: 0.7402052
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: "Brent Franklin's Site"
