name: "Brent Franklin's Site"
favicon: null
layout_spectrum: 0
typography_spectrum: 0.8866605
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8EC4E7'
    - '#B36E69'
    - '#000D16'
    - '#4581BB'
    - '#FBE280'
  brandStrength: 0.2784515
  lightness: 0.3877902417443693
  saturation: 0.856668782653287
  rhythmicContrast: 0.6672927553299814
purpose: []
