analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.6805037
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.3584229
  brandStrength: 1
  rhythmicContrast: 0.5107527
  brandColors:
    - '#000000'
    - '#A8AAA9'
    - '#373938'
    - '#585A59'
    - '#FCFEFD'
  lightness: 0.5340502
purpose: []
favicon: null
name: "Brent Franklin's Site"
typography_spectrum: 0.7402052
